### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by gpaluk** [sverx/devkitSMS#12]
I'm very interested to use this library but I wondered if there are any sample projects that use this library? I've searched but haven't been able to find anything.

**Comment by SteveProXNA** [comment]
Hi gpaluk - there are LOTS of examples that you can check out that demo how to use devkitSMS :)  Your first stop is smspower.org - check out the competitions section and any homebrew projects submitted from either myself [SteveProXNA] or eruiz00, haroldoop, kusfo and of course sverx usually include source code which will show you real world uses on how to integrate devkitSMS to build games for the Sega Master System in C.

PS: I have a bunch of blog posts that document how to setup devkitSMS and shows samples on how devkitSMS has been used various projects - check out steveproxna.blogspot.com and filter on devkitSMS [also maybe filter on Sega or SMS if that's useful]

PPS: kusfo also has a nice tutorial for devkitSMS here https://www.elotrolado.net/hilo_tutorial-muy-basico-de-c-para-master-system_2208028 which Google should be able to translate for you as necc.

Cheers,
Steve.

**Comment by sverx** [comment]
There is indeed some code scattered around.
Beside what Steve already pointed out, there's the [wiki](https://github.com/sverx/devkitSMS/wiki), which also links a few **SMS Power!** forum topics that contains some very small sample projects (links are in the [advanced section](https://github.com/sverx/devkitSMS/wiki/Advanced)).
Then there's [this](https://www.smspower.org/forums/15888-DevkitSMSTutorial) (slightly old but mostly still valid) [tutorial](https://www.smspower.org/forums/15888-DevkitSMSTutorial) I wrote back in 2016 that contains a very simple sample project.
Finally, there's Eruiz00's complete game "[Astro Force](https://www.smspower.org/Homebrew/AstroForce-SMS)" full sources are available too, if you need something more advanced.
Let me know if you need more info.

**Comment by SteveProXNA** [comment]
Ha!  As soon as I wrote this entry I knew that I forgot @sverx initial [tutorial ](https://www.smspower.org/forums/15888-DevkitSMSTutorial) which is really useful for noobs :)
PS: if you code on Windows and prefer Visual Studio then I ported "Astro Force" so that you can better navigate around the code base - initial cut can be found [here](https://github.com/SteveProXNA/AstroForceSMS).  I also prototyped "Astro Force" with new approach so you can actually debug step thru the code - it's rough but it does work and can be found [here](https://github.com/StevePro7/AstroForceSMS)

**Comment by gpaluk** [comment]
This is fantastic. Thanks!
