### ISSUE TITLE
Interrupt and VDP processing

### ISSUE THREAD

**Issue by 110-kenichi** [sverx/devkitSMS#19]
I'm working on H-INT and V-INT.

When my program is using VDP function while H-INT and V-INT, graphics glitches sometimes occur.
Yes, I know the reason, both main loop and H/V-INT uses VDP function, graphics glitches occur.

Can I avoid this issue? I think DISABLE_INTERRUPTS & ENABLE_INTERRUPTS is not work properly...

**Comment by sverx** [comment]
Can you elaborate on this? What are the glitches you're getting?

**Comment by 110-kenichi** [comment]
(1) main loop invokes setTile api repeatedly
(2) interrupt routine invokes SMS_setBGScrollX

→ setTile api failed. Because VRAM address is changed.

I could figure out the reason.

When my application invoke DI before VDP processing to avoid interrupt.
But, the crt0 invokes EI instruction in the VDP APIs(see the below). So, I can't disable interrupt... ;-<

_SMS_crt0_RST08::
        ld c, #0xBF                     ; set VDP Control Port
        di                              ; make it interrupt SAFE
        out (c),l
        out (c),h
        ei
        ret

**Comment by 110-kenichi** [comment]
It looks like we need an API like SMS_copySpritestoSAT() for all VDP instructions, just like sprite APIs.

**Comment by 110-kenichi** [comment]
Strategy:

(1) VDP APIs just queued VDP Address and DATA.
(2) Commit all queue data in VBlanking by like CommitVDPData() API and so on.

**Comment by sverx** [comment]
I see your point. It's the way the SMS VDP works, unfortunately even setting a register (in your case, the horizontal scroll register) affects the destination address of VRAM operations (in your case, the address you write using the setTile call).
SMSlib doesn't address this problem at all, as any possible solution would be cumbersome so I suggest you some possible workaround scenarios:
- make sure you do *all* your setTile calls before (or after) the horizontal interrupt happens
- split the setTile calls in two parts so that you can perform the first part *before* the horizontal interrupt happens and the second part *after* that, making sure you set again the destination address before the second part of setTile calls
- create your own atomic and uninterruptible setTile API that sets address and writes the data all before re-enabling interrupts (this is not the suggested way as it would slow down quite a bit and also keep your horizontal interrupt to be fired at the right line)

**Comment by 110-kenichi** [comment]
Thank you.

I can agree your opinions.

**Comment by 110-kenichi** [comment]
> (2) Commit all queue data in VBlanking by like CommitVDPData() API and so on.

I've created "Queue" mechanism. It seems okay for my program. Thanks.

**Comment by sverx** [comment]
That's a good approach if you don't have to update too much data, as the vblank phase is anyway pretty short.
Good you found an appropriate workaround! :smile:
