### ISSUE TITLE
General questions about the library

### ISSUE THREAD

**Issue by iganinja** [sverx/devkitSMS#2]
Hi sverx

First of all, I want to really thank you for your work grouping all that code into a single, coherent unit. This way it is much easier to do something for the SMS (sometime I plan to do when I have enough time).

I also wanted to ask you some questions about it:

- Does the library allow 8x16 sprites?

- Is the library tested in real hardware? What about Mega Drive + everdrive combo?

- What's your estimation about library's completeness? Is there something important lacking from it?

- Do you plan to add some tutorials about several how to-s or a somewhat complete example?

Again, thak you very much for your work :)

**Comment by sverx** [comment]
- 8x16 sprites are supported since Oct. 12, 2015 - switch sprite mode using:
```
void SMS_setSpriteMode (unsigned char mode)
```
the available modes are:
```
SPRITEMODE_NORMAL 
SPRITEMODE_TALL 
SPRITEMODE_ZOOMED 
SPRITEMODE_TALL_ZOOMED
```
which corresponds to 8x8, 8x16, 16x16 (zoomed 8x8) and 16x32 (zoomed 8x16)
(beware that "there is a bug in how the original SMS VDP processes zoomed sprites compared to the SMS 2 and GG VDP; it will only allow the first four sprites of the eight shown on a scanline to be zoomed horizontally and vertically, and the remaining four will be zoomed vertically. The SMS 2 and GG allow all eight sprites to be zoomed in both directions." as Charles docs said).

- the library **IS** tested on real hardware, even if I've only got an SMS II to run tests.
- the library is quite complete, feature wise. Missing features can be requested (see the official topic [here](http://www.smspower.org/forums/15228-DevkitSMSDevelopYourHomebrewInC) on SMSPower! website)
- I have no plans for a tutorial, but there's the wiki here on the GitHub repo and the topic on SMSPower to discuss. Also, there are a few example -complete with sources- on the wild.

Cheers! :)

**Comment by iganinja** [comment]
Thanks for the answers
