### ISSUE TITLE
Need clear vram on startup

### ISSUE THREAD

**Issue by Alirio926** [sverx/devkitSMS#32]
Hello!!!
When running on real Master System II, the logo SEGA dont is removed after devkit finish startup.
Configured the Emulicious emu with same bios(EU with Alex kid in memory), cause the same issue. Só i make a clearscreen code in asm and run at begin from me main program.
I dont know how to do a Pull requests (rsrsrs) so, need clear vram at startup to remove logo SEGA from screen. 
**Thats not a issue**, Sorry doing this here

**Comment by sverx** [comment]
Hello!
Yes, VRAM doesn't get cleared on startup for the simple reason that it's useless to do it.
When the library startup code is completed, screen is left turned off. So that's when you can load the tiles you need and load/generate the tilemap in VRAM, and also load/set the palette(s) you need, and after that you can turn on the screen.
:wave:

**Comment by sverx** [comment]
Also I forgot to mention that should you anyway for any reason need to write zeroes to VRAM, there's the handy function
`SMS_VRAMmemset (unsigned int dst, unsigned char value, unsigned int size);`
so for instance you could clear the whole VRAM using
`SMS_VRAMmemset (0x0000, 0x00, 16384);`
(`0x0000` is the VRAM start address, `0x00` is the zero byte you want to write all over and `16384` is how many bytes you want to write)
As said this is likely going to be useless anyway ;)

**Comment by Alirio926** [comment]
Thanks for explain!!! I understand now.
