### ISSUE TITLE
PSGLib - Allow to set volume attenuation on SFX

### ISSUE THREAD

**Issue by armixer24** [sverx/devkitSMS#54]
In PSGLib, the function `void PSGSetMusicVolumeAttenuation (unsigned char attenuation);` exists and it's great.

I want to use it to lower the volume all of the music to compensate for the SMS2's sound volume ramp being squashed in the upper values, and have it as an option to toggle in my game.
However, I noticed that there was no equivalent function for the sound effects.

Is it trivial enough to add?

**Comment by sverx** [comment]
The idea behind the music attenuation was to allow a different volume ratio between the BG music and the SFXs, so I never thought about attenuating the SFXs. I will look into that and see what can be added without too much burden.

**Comment by sverx** [comment]
I'm adding this. I hope you still need it! :sweat_smile:

**Comment by armixer24** [comment]
I'll be quite happy to see it!

Keep in mind that, as a backup, I was also considering reworking the music and sound effects to use the 0-13 volume range, where the ramp is not squashed, instead of 0-15.
So if this improvement never comes to be (because of performance or code size concerns for example), then it's OK!

**Comment by sverx** [comment]
I just pushed a commit that adds the `void PSGSetSFXVolumeAttenuation (unsigned char attenuation);` function.
Let me know if it works as expected - it should! :sweat_smile: 

Also, it's so unfortunate that the SMS2 audio has this issue, and that there's no good way to detect if code is running on such machines, as detecting the VDP version isn't sufficient since there are so many 'original' SMSs with the newer VDP anyway (or - at least in PAL regions...)
